name: 🐞 Found A Bug In The Question ?
description: report issue if found any bugs in the project
title : '[BUG]: on "topic-name" ("question-number") in "which-programming-lang"'
labels: ["🐞 bug"]
body:
  - type: markdown
    attributes:
      value : |
        Thanks for taking the time to fill out this bug report 💝 !
  - type: textarea
    id: description
    attributes:
      label: ✏️ Describe the bug
      description: Give a brife description of the bug you found in the question
      placeholder: Describe Your Issue Here ...
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots
      description: Give Screenshots if available
      placeholder: you can copy paste a image or just drag and drop files here..
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Before Submitting Make Sure To See a Preview Of This Message.. 🤗